# Generated by Django 4.0.4 on 2022-06-19 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pakalpojumi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lietotaji', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PakalpojumaVeids',
            fields=[
                ('nosaukums', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('apraksts', models.TextField()),
                ('cena', models.FloatField()),
            ],
            options={
                'verbose_name': 'Pakalpojuma veids',
                'verbose_name_plural': 'Pakalpojuma veidi',
            },
        ),
        migrations.CreateModel(
            name='Pasutijums',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aktivs', models.BooleanField(default=True, verbose_name='aktīvs')),
                ('pasutijuma_veiktais_datums', models.DateTimeField(auto_now_add=True, verbose_name='pasūtījuma veiktais datums')),
                ('pasutijuma_datums', models.DateField(verbose_name='pasūtījuma datums')),
                ('pasutijuma_laiks', models.TimeField(verbose_name='pasūtījuma laiks')),
                ('apraksts', models.TextField(null=True)),
                ('kopeja_cena', models.FloatField(null=True, verbose_name='kopējā cena')),
                ('fotografs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lietotaji.fotografs', verbose_name='fotogrāfs')),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='lietotājs')),
                ('pakalpojuma_veids', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pakalpojumi.pakalpojumaveids')),
            ],
            options={
                'verbose_name': 'Pasūtījums',
                'verbose_name_plural': 'Pasūtījumi',
            },
        ),
        migrations.CreateModel(
            name='BilzuGalerija',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nosaukums', models.CharField(max_length=128)),
                ('izveidosanas_datums', models.DateTimeField(auto_now_add=True, verbose_name='izveidošanas datums')),
                ('pasutijums', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pakalpojumi.pasutijums', verbose_name='pasūtījums')),
            ],
            options={
                'verbose_name': 'Bilžu galerija',
                'verbose_name_plural': 'Bilžu galerijas',
            },
        ),
        migrations.CreateModel(
            name='Bilde',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('atrasanas_vieta', models.CharField(max_length=300, null=True, verbose_name='atrašanās vieta')),
                ('fails', models.ImageField(upload_to=pakalpojumi.models.bilzu_galerijas_cels)),
                ('bilzu_galerija', models.ForeignKey(max_length=400, on_delete=django.db.models.deletion.CASCADE, to='pakalpojumi.bilzugalerija', verbose_name='bilžu galerija')),
                ('lietotajs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='lietotājs')),
            ],
            options={
                'verbose_name': 'Bilde',
                'verbose_name_plural': 'Bildes',
            },
        ),
    ]
