# Generated by Django 4.0.4 on 2022-06-19 20:28

from django.db import migrations, models
import pakalpojumi.models


class Migration(migrations.Migration):

    dependencies = [
        ('pakalpojumi', '0002_alter_bilde_bilzu_galerija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bilde',
            name='fails',
            field=models.ImageField(max_length=400, upload_to=pakalpojumi.models.bilzu_galerijas_cels),
        ),
    ]
